---
# defaults file for wordpress
wordpress_php_fpm_socket: "unix://var/run/php-fpm-wordpress.sock"
wordpress_external_ip: 0.0.0.0
wordpress_external_http_port: 80
wordpress_external_https_port: 443

wordpress_site_base_domain: example.com
wordpress_redirect_domains:
  - "{{ wordpress_site_base_domain }}"

wordpress_site_domain: "www.{{ wordpress_site_base_domain }}"

wordpress_cert_path: /etc/letsencrypt/live/{{ wordpress_site_base_domain }}/fullchain.pem
wordpress_key_path: /etc/letsencrypt/live/{{ wordpress_site_base_domain }}/privkey.pem
