---
site_url: https://www.queercraft.net

server_name: mc.queercraft.net
external_ip: 54.39.243.77

cert_path: /etc/letsencrypt/live/mc.queercraft.net/fullchain.pem
key_path: /etc/letsencrypt/live/mc.queercraft.net/privkey.pem

servers:
  - config_name: map
    server_name: map.queercraft.net
    cert_path: /etc/letsencrypt/live/mc.queercraft.net/fullchain.pem
    key_path: /etc/letsencrypt/live/mc.queercraft.net/privkey.pem
    external_ip: 54.39.243.77
    external_http_port: 80
    external_https_port: 443
    locations:
      - location: /
        proxy_pass: http://127.0.0.1:8100
        extra_lines:
          - "proxy_intercept_errors on;"
          # - "rewrite ^/map/(.*) /$1 break;"
  - config_name: radio
    server_name: radio.queercraft.net
    cert_path: /etc/letsencrypt/live/mc.queercraft.net/fullchain.pem
    key_path: /etc/letsencrypt/live/mc.queercraft.net/privkey.pem
    external_ip: 54.39.243.77
    external_http_port: 80
    external_https_port: 443
    locations:
      - location: /
        proxy_pass: https://prismlgbtq.xyz/radio/
        extra_lines:
          - "proxy_intercept_errors off;"
          # - "rewrite ^/radio/(.*) /queercraft-radio/$1 break;"
      - location: /stream
        proxy_pass: http://localhost:8008
        extra_lines:
          - "proxy_intercept_errors off;"
          # - "rewrite ^/stream/(.*) /stream/$1 break;"

amp_instances:
  - instance_name: ads
    server_name: amp.queercraft.net
    external_ip: 54.39.243.77
    localhost_port: 8080
    external_port: 443
    cert_path: /etc/letsencrypt/live/mc.queercraft.net/fullchain.pem
    key_path: /etc/letsencrypt/live/mc.queercraft.net/privkey.pem
  # - instance_name: nova5
  #   server_name: mc.queercraft.net
  #   external_ip: 54.39.243.77
  #   localhost_port: 8084
  #   external_port: 8084
  #   cert_path: /etc/letsencrypt/live/mc.queercraft.net/fullchain.pem
  #   key_path: /etc/letsencrypt/live/mc.queercraft.net/privkey.pem
  # - instance_name: nova6
  #   server_name: mc.queercraft.net
  #   external_ip: 54.39.243.77
  #   localhost_port: 8086
  #   external_port: 8086
  #   cert_path: /etc/letsencrypt/live/mc.queercraft.net/fullchain.pem
  #   key_path: /etc/letsencrypt/live/mc.queercraft.net/privkey.pem

# sc_instances:
#   - instance_name: shoutcast
#     server_name: radio.queercraft.net
#     external_ip: 0.0.0.0
#     localhost_port: 8008
#     external_port: 443
#     cert_path: /etc/letsencrypt/live/mc.queercraft.net/fullchain.pem
#     key_path: /etc/letsencrypt/live/mc.queercraft.net/privkey.pem

staffapp_uwsgi_socket: unix:///var/www/qcmodapp/uwsgi.sock

staffapp_server_name: queercraft.net staff.queercraft.net
staffapp_cert_path: /etc/letsencrypt/live/staff.queercraft.net/fullchain.pem
staffapp_key_path: /etc/letsencrypt/live/staff.queercraft.net/privkey.pem

staffapp_dir: /var/www/qcmodapp

staffapp_location_aliases:
  - location: /media
    alias: "{{ staffapp_dir }}/qcmodapp/media/"
  - location: /static
    alias: "{{ staffapp_dir }}/static/"
  - location: robots.txt
    alias: "{{ staffapp_dir }}/static/robots.txt"
  - location: favicon.ico
    alias: "{{ staffapp_dir }}/static/favicon.ico"

wordpress_php_fpm_socket_path: /var/run/php-fpm-wordpress.sock
wordpress_php_fpm_socket: "unix://{{ wordpress_php_fpm_socket_path }}"
wordpress_external_ip: 54.39.243.77
wordpress_external_http_port: 80
wordpress_external_https_port: 443

wordpress_site_domain: newsite.queercraft.net

wordpress_cert_path: /etc/letsencrypt/live/newsite.queercraft.net/fullchain.pem
wordpress_key_path: /etc/letsencrypt/live/newsite.queercraft.net/privkey.pem

...
