---
- name: Remove default nginx config
  become: true
  ansible.builtin.file:
    path:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available/default
    state: absent
  notify: Reload nginx

- name: Create all AMP reverse proxy configs
  become: true
  ansible.builtin.template:
    src: "nginx-amp-panel.conf.j2"
    dest: "/etc/nginx/sites-available/amp-{{ item.instance_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ amp_instances }}"
  vars:
    amp: "{{ item }}"
  notify: Reload nginx

- name: Create all reverse proxy configs
  become: true
  ansible.builtin.template:
    src: "nginx-site-ssl.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item.config_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ servers }}"
  vars:
    server: "{{ item }}"
  notify: Reload nginx

- name: Place staffapp config
  become: true
  ansible.builtin.template:
    src: "nginx-staffapp.conf.j2"
    dest: "/etc/nginx/sites-available/staffapp.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx

- name: Find all configs
  become: true
  ansible.builtin.find:
    paths: /etc/nginx/sites-available
    patterns: "*.conf"
  register: nginx_configs

- name: Symlink all configs
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  notify: Reload nginx
  loop: "{{ nginx_configs.files | map(attribute='path') | map('basename') | list }}"
...
