---
site_url: https://example.com

server_name: mc.example.com
external_ip: 0.0.0.0

cert_path: /etc/letsencrypt/live/mc.example.com/fullchain.pem
key_path: /etc/letsencrypt/live/mc.example.com/privkey.pem

servers:
  - config_name: map
    server_name: map.example.com
    cert_path: /etc/letsencrypt/live/mc.example.com/fullchain.pem
    key_path: /etc/letsencrypt/live/mc.example.com/privkey.pem
    external_ip: 192.168.0.2
    external_http_port: 80
    external_https_port: 443
    locations:
      - location: /
        proxy_pass: http://127.0.0.1:8100
        extra_lines:
          - "proxy_intercept_errors on;"
          # - "rewrite ^/map/(.*) /$1 break;"

amp_directory: /opt/cubecoders/amp/

amp_instances:
  - instance_name: ads
    server_name: amp.example.com
    external_ip: 192.168.0.2
    localhost_port: 8080
    external_port: 443
    cert_path: /etc/letsencrypt/live/amp.example.com/fullchain.pem
    key_path: /etc/letsencrypt/live/amp.example.com/privkey.pem

...
