---
- name: Configure Nginx
  hosts: queercraft
  tags: nginx
  pre_tasks:
    - name: Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present

  roles:
    - role: nginx_config

- name: Configure UFW
  hosts: queercraft
  tags: ufw
  pre_tasks:
    - name: Fetch TCPShield IPs
      ansible.builtin.uri:
        url: "{{ item }}"
        return_content: true
        status_code: 200
      register: tcpshield_ips
      loop:
        - https://tcpshield.com/v4
        - https://tcpshield.com/v4-cf

    - name: Set tcpshield_ips list
      ansible.builtin.set_fact:
        tcpshield_ips: "{{ tcpshield_ips.results | map(attribute='content') | map('trim') | map('split', '\n') | list | flatten | list }}"

    - name: Fetch Cloudflare IPs
      ansible.builtin.uri:
        url: "{{ item }}"
        return_content: true
        status_code: 200
      register: cloudflare_ips
      loop:
        - https://www.cloudflare.com/ips-v4
        - https://www.cloudflare.com/ips-v6

    - name: Set tcpshield_ips list
      ansible.builtin.set_fact:
        cloudflare_ips_both: "{{ cloudflare_ips.results | map(attribute='content') | map('trim') | map('split', '\n') | list | flatten | list }}"
        cloudflare_ips_v4: "{{ cloudflare_ips.results[0].content | trim | split('\n') }}"
        cloudflare_ips_v6: "{{ cloudflare_ips.results[1].content | trim | split('\n') }}"
  roles:
    - role: ufw_config

...
